// Generated by Wrangler
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	IMAGES: any;
	ASSETS: Fetcher;
	NEXTJS_ENV: string;
	WORKER_SELF_REFERENCE: Fetcher;
}

declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}

interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
